name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.11.3"

      - name: Setup snfoundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.39.0"

      - name: Check versions
        run: |
          scarb --version
          snforge -V
      - name: Format Check
        run: scarb fmt --check

      - name: Run Tests
        run: snforge test

      - name: Build Project
        run: scarb build